version: '3.8'

services:
  web:
    build: sna
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_HOST=prometheus
    command: python manage.py runserver 0.0.0.0:8000

  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.2
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  grafana-data: